export const REQUEST_GET_ALL_CATEGORIES = "REQUEST_GET_ALL_CATEGORIES";
export const SUCCESS_GET_ALL = "SUCCESS_GET_ALL";
export const FAILED_GET_ALL = "FAILED_GET_ALL";

export const REQUEST_GET_SUB_CAT = "REQUEST_GET_SUB_CAT";
export const SUCCESS_GET_SUB_CAT = "SUCCESS_GET_SUB_CAT";
export const FAILED_GET_SUB_CAT = "FAILED_GET_SUB_CAT";

export const REQUEST_GET_PRODUCTS_BY_SLUG = "REQUEST_GET_PRODUCTS_BY_SLUG";
export const SUCCESS_GET_PRODUCTS_BY_SLUG = "SUCCESS_GET_PRODUCTS_BY_SLUG";
export const FAILED_GET_PRODUCTS_BY_SLUG = "FAILED_GET_PRODUCTS_BY_SLUG";
