export const REQUEST_UPDATE = "REQUEST_UPDATE";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_FAILURE = "UPDATE_FAILURE";

export const REQUEST_GET_USER = "REQUEST_GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const REQUEST_GET_USER_FOR_NAV = "REQUEST_GET_USER_FOR_NAV";
export const GET_USER_FOR_NAV_SUCCESS = "GET_USER_FOR_NAV_SUCCESS";
export const GET_USER_FOR_NAV_FAILURE = "GET_USER_FOR_NAV_FAILURE";

export const REQUEST_CHANGE_PASS = "REQUEST_CHANGE_PASS";
export const CHANGE_PASS_SUCCESS = "CHANGE_PASS_SUCCESS";
export const CHANGE_PASS_FAILURE = "CHANGE_PASS_FAILURE";

export const ForTest = "ForTest";
